spring:
  thymeleaf:
    mode: HTML
    cache: false
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:in-between
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console