spring:
  thymeleaf:
    mode: HTML
    cache: false
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver